### ISSUE TITLE
intertext: misplaced noalign

### ISSUE THREAD

**Issue by Konfekt** [MagicMuscleMan/autonum#3]
```
\usepackage{mathtools}
```

and

```
\begin{align}
     a & b\\
  \intertext{Then}
  c & d
\end{align}
```

procudes

```
 Misplaced \noalign.
 Emergency stop.
 ==> Fatal error occurred, no output PDF file produced!
```

Apparently, autonum has to insert a missing linebreak (see https://books.google.fr/books?id=6WTZ0Rpiwp8C&pg=PA227&lpg=PA227&dq=intertext+misplaced+noalign&source=bl&ots=_gqpyFB5aW&sig=4QT0YD20DrXq-Lz8IczS7nv5ddk&hl=fr&sa=X&ei=2iu9VOO4ApLnaP3OgMAH&ved=0CDMQ6AEwAg#v=onepage&q=intertext%20misplaced%20noalign&f=false).

**Comment by Konfekt** [comment]
Same for other mathtools command such as `\shortintertext` and `SwapAboveDisplaySkip`.

**Comment by MagicMuscleMan** [comment]
Sorry, I cannot reproduce the problem with version 0.3.11. In order to be able to help you and fix the bug, please provide a complete minimal example (including document class and a minimal set of loaded packages), which compiles when not loading autonum and shows the error when loading autonum.

Did you use version 0.3.11? Maybe the problem occurs only with older versions?

Sorry, I cannot open the link you provided. It seems to be accessible for users from France only.

**Comment by Konfekt** [comment]
Hello,

I'm using 

```
Package: autonum 2015/01/03 v0.3.10 autonum LaTeX package
```

but TexLive does not show any updates. Is it avaialbe in personal package repository?

---

Does this link work ?

https://books.google.de/books?id=6WTZ0Rpiwp8C&pg=PA227&lpg=PA227&dq=intertext+misplaced+noalign&source=bl&ots=_gqpyFB5aW&sig=4QT0YD20DrXq-Lz8IczS7nv5ddk&hl=de&sa=X&ei=2iu9VOO4ApLnaP3OgMAH&ved=0CDMQ6AEwAg#v=onepage&q=intertext%20misplaced%20noalign&f=false

**Comment by Konfekt** [comment]
Thank you. Now that 3.11 hit texlive, the issue is gone!
